-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."metadata" alter column "updated_at" drop not null;
-- alter table "public"."metadata" alter column "property_address" drop not null;
