-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."metadata" add column "appliances_number" integer
--  not null default '0';
